// "Why this alert?" content (design/2026-10-07-alert-explanation-design.md,
// Frontend UX): the five evidence sections for one alert, with no dialog
// chrome, so the desktop drawer (AlertExplanationPanel) and the mobile route
// (feature 5) render the same thing. Every section copes with its block being
// null — the server degrades each one on its own and says why in `notes`.
// Wording rule (SRS FR-25/NFR-13): a cause is only ever *probable*.
import { useState } from 'react'
import type { ReactNode } from 'react'
import { Link } from 'react-router-dom'
import type {
  AlertExplanation,
  ExplanationChannelKey,
  ExplanationPrediction,
  KeyFactors,
  ProbableCauseExplanation,
  SimilarIncident,
  TriggeringReadings,
} from '../api/types'
import {
  causeText,
  checkText,
  directionText,
  formatRatio,
  formatValue,
  hasOutOfRange,
  matchReasonLabel,
  orderWarnings,
  rulText,
} from '../lib/explanationFormat'
import { formatPercent, formatRelative } from '../lib/telemetryFormat'
import {
  factorIntensity,
  feedbackOutcomeLabel,
  feedbackOutcomeTone,
  healthClasses,
  healthLabel,
  severityClasses,
  workOrderStatusLabel,
} from './healthStyles'
import { TrendChart } from './TrendChart'
import { Badge } from './ui/badge'
import { Label, Select } from './ui/input'

const DEFAULT_CHANNEL = 'vibration_h_kurtosis'

export function AlertExplanationView({ explanation }: { explanation: AlertExplanation }) {
  const now = Date.now()
  const { alert, synthetic } = explanation
  const outOfRange = hasOutOfRange(explanation)

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        {explanation.source === 'snapshot' ? (
          <Badge variant="accent" title={explanation.snapshot_at ?? undefined}>
            Snapshot · captured {formatRelative(explanation.snapshot_at, now)}
          </Badge>
        ) : (
          <Badge variant="neutral" title="No snapshot was captured for this alert; rebuilt from stored data">
            Reconstructed
          </Badge>
        )}
        {explanation.snapshot_kind === 'escalated' && (
          <Badge
            variant="faulty"
            title={`Escalated${explanation.snapshot_at ? ` ${explanation.snapshot_at}` : ''} (opened ${alert.opened_at})`}
          >
            Escalated
          </Badge>
        )}
        {synthetic && <Badge variant="accent2">Synthetic (demo)</Badge>}
        <span className={`rounded-full px-2 py-0.5 text-xs ${severityClasses(alert.severity)}`}>{alert.severity}</span>
        <span className="text-xs text-text-muted">
          Alert #{alert.id} · {healthLabel(alert.health_state)} · opened{' '}
          <time dateTime={alert.opened_at} title={alert.opened_at}>
            {formatRelative(alert.opened_at, now)}
          </time>
        </span>
      </div>
      {synthetic && (
        <p className="text-xs text-text-muted">
          Generated by the admin demo trigger; readings are scaled copies of a real reading.
        </p>
      )}
      {outOfRange && (
        <div role="status" className="rounded-xl border border-degrading/40 bg-degrading/10 p-3 text-sm text-degrading">
          Outside the model's training range — treat this estimate with caution.
        </div>
      )}

      <Section title="Triggering readings">
        <TriggerSection readings={explanation.triggering_readings} />
      </Section>
      <Section title="Key factors">
        <KeyFactorsSection factors={explanation.key_factors} />
      </Section>
      <Section title="Probable cause">
        <ProbableCauseSection cause={explanation.probable_cause} />
      </Section>
      <Section title="Model prediction">
        <PredictionSection prediction={explanation.prediction} synthetic={synthetic} />
      </Section>
      <Section title="Similar past incidents">
        <SimilarSection incidents={explanation.similar_incidents} now={now} />
      </Section>

      {explanation.notes.length > 0 && (
        <ul aria-label="Notes" className="list-disc space-y-1 pl-5 text-xs text-text-muted">
          {explanation.notes.map((note) => (
            <li key={note}>{note}</li>
          ))}
        </ul>
      )}
    </div>
  )
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  const id = `explanation-${title.toLowerCase().replaceAll(' ', '-')}`
  return (
    <section aria-labelledby={id} className="rounded-xl border border-white/10 bg-white/[0.03] p-3">
      <h3 id={id} className="mb-2 text-xs font-semibold uppercase tracking-wide text-text-muted">
        {title}
      </h3>
      {children}
    </section>
  )
}

function Muted({ children }: { children: ReactNode }) {
  return <p className="text-sm text-text-muted">{children}</p>
}

function TriggerSection({ readings }: { readings: TriggeringReadings | null }) {
  const channels = readings?.channels ?? []
  const [channel, setChannel] = useState(
    channels.some((c) => c.key === DEFAULT_CHANNEL) ? DEFAULT_CHANNEL : (channels[0]?.key ?? DEFAULT_CHANNEL),
  )
  if (!readings || readings.readings.length === 0) {
    return <Muted>No vibration readings are stored for this machine.</Muted>
  }
  const current = channels.find((c) => c.key === channel)
  const metric = current ? `${current.label}${current.unit ? ` (${current.unit})` : ''}` : channel
  const points = readings.readings.map((r) => ({
    timestamp: r.timestamp,
    value: r[channel as ExplanationChannelKey] ?? null,
  }))

  const triggerIndex = readings.readings.findIndex((r) => r.is_trigger)
  const trigger = readings.trigger_timestamp
    ? { timestamp: readings.trigger_timestamp, label: 'Trigger', index: triggerIndex >= 0 ? triggerIndex : undefined }
    : undefined

  let caption: string
  switch (readings.locate) {
    case 'reading_id':
      caption = `Trigger: reading #${readings.trigger_reading_id} at ${readings.trigger_timestamp ?? '—'}`
      break
    case 'prediction_reading':
      caption = `Trigger: reading #${readings.trigger_reading_id} scored by the alert's prediction`
      break
    case 'nearest_timestamp':
      caption = 'Nearest reading to the alert time (no linked reading)'
      break
    case 'snapshot_features':
      caption = 'The feature vector the model scored (no stored reading)'
      break
    default:
      caption = 'No trigger reading could be located'
  }

  return (
    <div>
      <Label className="max-w-xs">
        Channel
        <Select value={channel} onChange={(e) => setChannel(e.target.value)}>
          {channels.map((c) => (
            <option key={c.key} value={c.key}>
              {c.label}
            </option>
          ))}
        </Select>
      </Label>
      <div className="mt-2">
        <TrendChart
          metric={metric}
          points={points}
          marker={trigger}
        />
      </div>
      <p className="text-xs text-text-muted">
        {caption} · last {readings.readings.length} readings, vibration channels only
      </p>
    </div>
  )
}

const FACTOR_STATUS_TEXT: Record<string, string> = {
  insufficient_history: 'Not enough history on this machine to rank key factors yet (at least 5 earlier readings are needed).',
  no_readings: 'No readings are stored for this machine, so key factors cannot be ranked.',
  error: 'Key factors could not be computed for this alert.',
}

function KeyFactorsSection({ factors }: { factors: KeyFactors | null }) {
  if (!factors) return <Muted>Key factors are not available for this alert.</Muted>
  if (factors.status !== 'ok') return <Muted>{FACTOR_STATUS_TEXT[factors.status]}</Muted>

  const maxScore = Math.max(0, ...factors.factors.map((f) => f.score))
  const weighting =
    factors.weighting === 'model_importance' ? 'weighted by model importance' : 'unweighted (model not loaded)'

  return (
    <div className="space-y-3">
      {factors.factors.length === 0 ? (
        <Muted>No vibration feature moved from this machine's baseline.</Muted>
      ) : (
        <ul aria-label="Key factors" className="space-y-2.5">
          {factors.factors.map((f) => {
            const share = maxScore > 0 ? f.score / maxScore : 0
            const unit = f.unit && f.unit !== 'fraction' ? ` ${f.unit}` : ''
            return (
              <li key={f.feature} className="text-sm">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <span className="flex flex-wrap items-center gap-2 text-text">
                    {f.label}
                    {f.outside_training_bounds === true && (
                      <Badge
                        variant="degrading"
                        title={f.out_of_bounds_features.length ? f.out_of_bounds_features.join(', ') : undefined}
                      >
                        Outside training range
                      </Badge>
                    )}
                  </span>
                  <span className="font-mono text-xs text-text">{directionText(f.direction, f.ratio)}</span>
                </div>
                <div className="mt-1 h-1.5 w-full overflow-hidden rounded-full bg-white/[0.06]">
                  <div
                    role="img"
                    aria-label={`${f.label}: ${formatRatio(f.ratio)}× baseline, ${f.direction}`}
                    className={`h-full rounded-full ${healthClasses(factorIntensity(share, f.direction)).dot}`}
                    style={{ width: `${Math.max(4, Math.round(share * 100))}%` }}
                  />
                </div>
                <p className="mt-0.5 font-mono text-xs text-text-muted">
                  {formatValue(f.value)}
                  {unit} vs baseline {formatValue(f.baseline)}
                  {unit}
                  {f.importance != null && ` · model weight ${formatPercent(f.importance, 0)}`}
                </p>
              </li>
            )
          })}
        </ul>
      )}
      <p className="text-xs text-text-muted">
        Ranked by deviation from this machine's first {factors.baseline_readings} readings, {weighting}. A heuristic
        ranking of what moved, not a measured cause.
      </p>
      {factors.operating_conditions.length > 0 && (
        <div>
          <h4 className="text-xs uppercase tracking-wide text-text-muted">Operating conditions (context, not ranked)</h4>
          <dl className="mt-1 flex flex-wrap gap-x-6 gap-y-1 text-sm">
            {factors.operating_conditions.map((c) => (
              <div key={c.feature} className="flex items-center gap-2">
                <dt className="text-text-muted">{c.label}</dt>
                <dd className="font-mono text-text">
                  {formatValue(c.value)} {c.unit}
                </dd>
                {c.outside_training_bounds === true && <Badge variant="degrading">Outside training range</Badge>}
              </div>
            ))}
          </dl>
        </div>
      )}
    </div>
  )
}

function ProbableCauseSection({ cause }: { cause: ProbableCauseExplanation | null }) {
  if (!cause) return <Muted>No probable cause was evaluated for this alert.</Muted>
  return (
    <div className="space-y-2">
      <p className="text-base font-semibold text-text">{cause.display}</p>
      <p className="text-xs text-text-muted">{cause.disclaimer}</p>
      {cause.checks.length > 0 ? (
        <ol aria-label="Rule trace" className="space-y-1 text-sm">
          {cause.checks.map((check, i) => (
            <li key={`${check.feature}-${i}`} className="flex items-baseline gap-2">
              <span aria-hidden className={check.passed ? 'text-healthy' : 'text-text-muted'}>
                {check.passed ? '✓' : '✗'}
              </span>
              <span className={check.passed ? 'text-text' : 'text-text-muted'}>{checkText(check)}</span>
            </li>
          ))}
        </ol>
      ) : (
        cause.summary && <Muted>{cause.summary}</Muted>
      )}
      {cause.matches_alert === false && (
        <p className="text-xs text-degrading">
          The rule re-run on this reading gives {causeText(cause.evaluated_label)}; the alert's stored probable cause
          is shown above.
        </p>
      )}
      {cause.inputs_source && (
        <p className="text-xs text-text-muted">
          Evaluated on {cause.inputs_source === 'snapshot_features' ? 'the features the model scored' : 'the trigger reading'}.
        </p>
      )}
    </div>
  )
}

function PredictionSection({ prediction, synthetic }: { prediction: ExplanationPrediction | null; synthetic: boolean }) {
  const empty = 'No model prediction recorded'
  if (!prediction) return <Muted>{synthetic ? 'Synthetic demo reading — no model prediction' : empty}</Muted>
  if (synthetic && prediction.failure_within_horizon_probability == null && prediction.predicted_rul_minutes == null) {
    return <Muted>Synthetic demo reading — no model prediction</Muted>
  }
  const warnings = orderWarnings(prediction.warnings)
  const horizon = prediction.prognostic_horizon_minutes
  return (
    <div className="space-y-2">
      <dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
        <Fact label="Failure probability">
          {formatPercent(prediction.failure_within_horizon_probability, 0)}
          {horizon != null && <span className="text-text-muted"> within {Math.round(horizon)} min</span>}
        </Fact>
        <Fact label="Remaining useful life">{rulText(prediction)}</Fact>
        <Fact label="Health state">{prediction.health_state ? healthLabel(prediction.health_state) : '—'}</Fact>
        <Fact label="Model version">
          <span className="font-mono">{prediction.model_version ?? '—'}</span>
        </Fact>
        <Fact label="Out of distribution">{prediction.out_of_distribution ? 'Yes' : 'No'}</Fact>
        {prediction.outside_training_features.length > 0 && (
          <Fact label="Outside training range">
            <span className="font-mono text-xs">{prediction.outside_training_features.join(', ')}</span>
          </Fact>
        )}
      </dl>
      {prediction.locate === 'nearest_timestamp' && (
        <p className="text-xs text-text-muted">Nearest prediction to the alert time (no linked prediction).</p>
      )}
      {warnings.length > 0 && (
        <ul aria-label="Model warnings" className="space-y-1 text-xs">
          {warnings.map((w) => (
            <li
              key={w}
              className={w.startsWith('out_of_distribution') ? 'text-degrading' : 'text-text-muted'}
            >
              {w}
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

function SimilarSection({ incidents, now }: { incidents: SimilarIncident[]; now: number }) {
  if (incidents.length === 0) {
    return <Muted>No earlier alerts with this probable cause or on this machine.</Muted>
  }
  return (
    <ul aria-label="Similar past incidents" className="space-y-3">
      {incidents.map((incident) => (
        <li key={incident.alert_id} className="border-l-2 border-accent/30 pl-3 text-sm">
          <div className="flex flex-wrap items-center gap-2">
            <span className="font-mono text-text">{incident.machine_id}</span>
            <span className="text-xs text-text-muted">
              Alert #{incident.alert_id} · opened{' '}
              <time dateTime={incident.opened_at} title={incident.opened_at}>
                {formatRelative(incident.opened_at, now)}
              </time>
            </span>
            <span className={`rounded-full px-2 py-0.5 text-xs ${severityClasses(incident.severity)}`}>
              {incident.severity}
            </span>
            <span className="font-mono text-xs text-accent">{Math.round(incident.similarity * 100)}% similar</span>
            {incident.synthetic && <Badge variant="accent2">Synthetic</Badge>}
            <Link
              to={`/alerts/${incident.alert_id}`}
              aria-label={`Why this alert? Alert #${incident.alert_id}`}
              className="ml-auto text-xs font-medium text-accent hover:text-accent-hover"
            >
              Why?
            </Link>
          </div>
          <div className="mt-1 flex flex-wrap gap-1.5">
            {incident.match_reasons.map((reason) => (
              <Badge key={reason} variant="neutral">
                {matchReasonLabel(reason)}
              </Badge>
            ))}
          </div>
          {incident.feedback ? (
            <div className="mt-1.5 flex flex-wrap items-center gap-2">
              <Badge variant={feedbackOutcomeTone(incident.feedback.outcome)}>
                {feedbackOutcomeLabel(incident.feedback.outcome)}
              </Badge>
              {incident.feedback.actual_cause && (
                <span className="text-xs text-text">
                  Actual cause: {causeText(incident.feedback.actual_cause)}
                  {incident.cause_confirmed === true && ' (matched)'}
                  {incident.cause_confirmed === false && ' (differed)'}
                </span>
              )}
            </div>
          ) : (
            <p className="mt-1.5 text-xs text-text-muted">No outcome recorded{incident.status === 'open' ? ' (still open)' : ''}.</p>
          )}
          {incident.feedback?.notes && <p className="mt-1 text-xs text-text-muted">{incident.feedback.notes}</p>}
          {incident.work_orders.length > 0 && (
            <p className="mt-1 flex flex-wrap gap-x-3 text-xs">
              {incident.work_orders.map((wo) => (
                <Link key={wo.id} to={`/work-orders/${wo.id}`} title={wo.title} className="text-accent hover:text-accent-hover">
                  WO #{wo.id} · {workOrderStatusLabel(wo.status).toLowerCase()}
                </Link>
              ))}
            </p>
          )}
          {incident.maintenance.map((m) => (
            <p key={m.id} className="mt-1 text-xs text-text-muted">
              Maintenance:{' '}
              {[m.type, m.description, m.technician].filter(Boolean).join(' · ')}
              {' · '}
              <time dateTime={m.performed_at} title={m.performed_at}>
                {formatRelative(m.performed_at, now)}
              </time>
            </p>
          ))}
        </li>
      ))}
    </ul>
  )
}

function Fact({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div>
      <dt className="text-xs uppercase tracking-wide text-text-muted">{label}</dt>
      <dd className="text-text">{children}</dd>
    </div>
  )
}
